env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
overrides: []
settings:
  react:
    version: 'detect'

parserOptions:
  ecmaVersion: latest
  sourceType: module
ignorePatterns: ['src/serviceWorker.js', 'build/*', '*.test.js']

plugins:
  - react
rules: { 'react/prop-types': 'off' }
